BEGIN
    BEGIN
        execute immediate 'drop table MICROSERVICE.POLLUUID';
        EXCEPTION WHEN OTHERS THEN NULL;
    END;
B   EGIN
        execute immediate 'ALTER TABLE MICROSERVICE.PAYMENTS DROP (SERVICESURVEY, SERVICESCOMMENTS)';        
        EXCEPTION WHEN OTHERS THEN NULL;
    END;
COMMIT;