--------------------------------------------------------
--  DDL for Table POLLUUID
--------------------------------------------------------

CREATE TABLE "MICROSERVICE"."POLLUUID2" ( 
    "UUID" VARCHAR2(40 BYTE), 
    "ORDERID" VARCHAR2(20 BYTE), 
    "DUEDATETIME" VARCHAR2(30 BYTE), 
    "USED" VARCHAR2(1 BYTE) DEFAULT 'N'
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table POLLUUID
--------------------------------------------------------
ALTER TABLE "MICROSERVICE"."POLLUUID" MODIFY ("UUID" NOT NULL ENABLE);
ALTER TABLE "MICROSERVICE"."POLLUUID" MODIFY ("ORDERID" NOT NULL ENABLE);
ALTER TABLE "MICROSERVICE"."POLLUUID" MODIFY ("DUEDATETIME" NOT NULL ENABLE);
ALTER TABLE "MICROSERVICE"."POLLUUID" MODIFY ("USED" NOT NULL ENABLE);

COMMIT;